### ISSUE TITLE
[Test Party] Account created despite providing a DOB in the future and getting a Server Error (500).

### ISSUE THREAD

**Issue by AlfaroukSaleh** [gcivil-nyu-org/INET-Monday-Spring2023-Team-2#202]
After getting Server Error (500) when providing a DOB in the future (10/05/3000) [explained in issue # 201], I tried to Sign up again and when providing the same email I get a message that this email already exists.
![Screen Shot 2023-04-14 at 1 40 05 AM](https://user-images.githubusercontent.com/50967999/231951359-70e6b468-4967-4fbf-bf5f-4bbecb1eb7fc.png)

**Comment by joeleu** [comment]
Deduping related issues: #205 #201
