### ISSUE TITLE
[Test Party] Can't login to the account, although the system says that the email already exists.

### ISSUE THREAD

**Issue by AlfaroukSaleh** [gcivil-nyu-org/INET-Monday-Spring2023-Team-2#203]
I created a new user with email "aa@aa.aa" and provided a DOB in the future (10/05/3000) [explained in issues #201 and #202].
I got a server Error (500), when trying to create a new account with that email address again I got a message that the email already exists.
When trying to login using that email and the password provided, I wasn't able to login.

![Screen Shot 2023-04-14 at 1 46 03 AM](https://user-images.githubusercontent.com/50967999/231952524-08412f73-7cdb-47d9-adbb-fbb9fe8b2580.png)

**Comment by joeleu** [comment]
This is a known issue and was mentioned as *not working* in the provided testing document.
