### ISSUE TITLE
[Test Party] Is seems that there is a problem in Volunteers Signup/Login features.

### ISSUE THREAD

**Issue by AlfaroukSaleh** [gcivil-nyu-org/INET-Monday-Spring2023-Team-2#204]
Whenever I create a new volunteer I get server error (500). Providing the DOB in format "mm/dd/yyyy" and providing a date in the past.
I then try to signup again using the same email but it says that "email already exists".
When trying to login, I'm not able to login.

**Comment by joeleu** [comment]
This is a known issue and was mentioned as *not working* in the provided testing document.
