### ISSUE TITLE
As a User, I want to be able to customize my profile page by adding a profile picture so that others can get to know me more

### ISSUE THREAD

**Issue by Hgersten-hash** [gcivil-nyu-org/INET-Monday-Spring2023-Team-2#49]
**User story**
As a User, I want to be able to customize my profile page by adding a profile picture so that others can get to know me more

**Acceptance criteria**
1. User sees space for a profile pic on their page
2. User is able to click on the profile pic space, and sees a prompt to upload a photo 
3. User is able to upload photo 
4. User sees the new photo appear on page.

**Definition of Done**
I know this user story is complete once a user is able to upload a photo on their profile pic space, and the pic is visible for every read of their page.

**Comment by JinweiZhu** [comment]
Migration history corruption is blocking anything database related for now.

**Comment by JinweiZhu** [comment]
Closed when pull request is merged.
