### ISSUE TITLE
As an Organization, I want to be able to edit a job that is posted so that I can make any necessary changes

### ISSUE THREAD

**Issue by Hgersten-hash** [gcivil-nyu-org/INET-Monday-Spring2023-Team-2#86]
**User story**
As an Organization, I want to be able to edit a job that is posted so that I can make any necessary changes.

**Acceptance criteria**
1. Organization can click on opp in "Upcoming Opp" section and is shown an edit option
2. Upon clicking edit, org is shown form similar to creation form except the button says update instead of create
3. Organization can make changes to the job
4. Upon clicking update, changes are shown on jobboard

**Definition of Done**
I know this story is complete when an organization is able to modify a posted job and its changes are shown on jobboard

**Comment by JinweiZhu** [comment]
Closed when pull request was merged.
